  export const DEFAULT_CATEGORIES = [
    { key: 'produce',  label: 'Produce',                icon: '🥬' },
    { key: 'meat',     label: 'Meat',                    icon: '🥩' },
    { key: 'cheese',   label: 'Cheese',                  icon: '🧀' },
    { key: 'canned',   label: 'Canned',                  icon: '🥫' },
    { key: 'chips',    label: 'Chips',                   icon: '🍿' },
    { key: 'bakery',   label: 'Bakery',                  icon: '🍞' },
    { key: 'frozen',   label: 'Frozen',                  icon: '🧊' },
    { key: 'dairy',    label: 'Dairy',                   icon: '🥛' },
    { key: 'spices',   label: 'Spices / Baking',         icon: '🧂' },
    { key: 'drinks',   label: 'Drinks / Juice / Seltzer',icon: '🥤' },
    { key: 'alcohol',  label: 'Alcohol',                 icon: '🍷' },
    { key: 'pharmacy', label: 'Pharmacy',                icon: '💊' },
    { key: 'baby',     label: 'Baby',                    icon: '🍼' },
    { key: 'household',label: 'Household & Paper Goods', icon: '🧻' },
    { key: 'misc',     label: 'Miscellaneous',           icon: '🗂️' },
  ];

  export const CATEGORY_KEYWORDS = {
    produce: ['broccoli','lettuce','spinach','kale','tomato','tomatoes','onion','onions','garlic','potato','potatoes','carrot','carrots','celery','cucumber','pepper','peppers','mushroom','mushrooms','avocado','avocados','lemon','lemons','lime','limes','apple','apples','banana','bananas','orange','oranges','grape','grapes','berry','berries','strawberry','strawberries','blueberry','blueberries','raspberry','melon','watermelon','cantaloupe','cilantro','parsley','basil','herbs','corn','zucchini','squash','cabbage','cauliflower','asparagus','ginger root','scallion','scallions','green onion','radish','radishes','beet','beets','eggplant','artichoke','brussels sprout','brussels sprouts','sweet potato','sweet potatoes','peach','peaches','pear','pears','pineapple','mango','kiwi','plum','cherries','cherry','nectarine','leek','leeks','shallot','shallots','pea','peas','green beans','bell pepper','jalapeno','jalapeño'],
    meat: ['chicken','beef','pork','steak','bacon','sausage','sausages','turkey','ground beef','ground turkey','ham','salmon','shrimp','fish','tilapia','ribs','chops','brisket','wings','meatballs'],
    cheese: ['cheddar','mozzarella','parmesan','brie','feta','gouda','string cheese','cream cheese','shredded cheese','cheese','provolone','swiss cheese'],
    canned: ['canned','beans','soup','tomato sauce','broth','chickpeas','tuna','black beans','refried beans','diced tomatoes','tomato paste','condensed milk'],
    chips: ['chips','pretzels','popcorn','tortilla chips','doritos','cheetos','crackers','pita chips'],
    bakery: ['bread','bagel','bagels','tortilla','tortillas','bun','buns','roll','rolls','baguette','english muffin','naan','pita'],
    frozen: ['frozen','ice cream','waffles','frozen pizza','frozen fries','popsicle','popsicles','frozen veggies','frozen vegetables','freezer'],
    dairy: ['milk','yogurt','butter','eggs','egg','cream','half and half','sour cream','cottage cheese','almond milk','oat milk'],
    spices: ['sugar','flour','salt','spice','spices','oil','olive oil','baking soda','baking powder','vanilla','ketchup','mustard','mayo','mayonnaise','pasta','rice','cereal','oats','honey','syrup','peanut butter','jelly','jam','seasoning','vinegar','breadcrumbs'],
    drinks: ['juice','soda','coffee','tea','water','gatorade','energy drink','lemonade','sparkling water','kombucha','seltzer'],
    alcohol: ['beer','wine','vodka','whiskey','tequila','rum','gin','hard seltzer','liquor','champagne'],
    pharmacy: ['tylenol','advil','ibuprofen','aspirin','vitamins','vitamin','bandaids','band-aids','medicine','cough','allergy','sunscreen','toothpaste','floss','deodorant','shampoo'],
    baby: ['diapers','diaper','formula','wipes','baby food','baby wash','pacifier'],
    household: ['paper towels','aluminum foil','foil','freezer bags','ziploc','sandwich bags','trash bags','garbage bags','paper plates','napkins','plastic wrap','saran wrap','paper cups','plastic cups','parchment paper','wax paper','plastic forks','plastic spoons','plastic utensils'],
  };
